default_language_version:
  python: python3.11

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        exclude: .github/
      - id: end-of-file-fixer
        exclude: LICENSE
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.282
    hooks:
      - id: ruff

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        exclude: ^{{ cookiecutter.project_name }}/
        types: [python, pyi, jupyter]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy
        exclude: |
          ^tests/|
        types: [python]
        args: [--strict]
        language: system
